// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  'aws_app_analytics': 'enable',
  'aws_bots': 'enable',
  'aws_bots_config': [{"name":"CareerAvatar","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"us-east-1"}],
  'aws_cognito_identity_pool_id': 'us-east-1:6a2761e7-053f-4542-84d1-6ac295ba6a26',
  'aws_cognito_region': 'us-east-1',
  'aws_content_delivery': 'enable',
  'aws_content_delivery_bucket': 'reactchatbot-hosting-mobilehub-1640287652',
  'aws_content_delivery_bucket_region': 'us-east-1',
  'aws_content_delivery_cloudfront': 'enable',
  'aws_content_delivery_cloudfront_domain': 'd3adfptsyptw7.cloudfront.net',
  'aws_mobile_analytics_app_id': '66eabd1dcb764b438cb098d2a3b79378',
  'aws_mobile_analytics_app_region': 'us-east-1',
  'aws_project_id': 'f18cbc70-de8f-4a5d-9bfc-b7f2a29ad2fc',
  'aws_project_name': 'react-chatbot-2019-01-13-15-59-37',
  'aws_project_region': 'us-east-1',
  'aws_resource_name_prefix': 'reactchatbot-mobilehub-1640287652',
  'aws_sign_in_enabled': 'enable',
  'aws_user_pools': 'enable',
  'aws_user_pools_id': 'us-east-1_LNkB7AFrY',
  'aws_user_pools_mfa_type': 'ON',
  'aws_user_pools_web_client_id': '6l9qbjti0sdmt89ddnmfdnnpii',
}

export default awsmobile;
